# Generated by Django 3.0.3 on 2020-03-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoFinalGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=2000, verbose_name='Nombre de trabajo de grado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('equipo_de_trabajo', models.TextField(verbose_name='Equipo de trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo final de grado',
                'verbose_name_plural': 'Trabajos finales de grado',
            },
        ),
    ]
