# Generated by Django 3.0.3 on 2020-03-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_final_grado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajofinalgrado',
            old_name='description',
            new_name='descripcion',
        ),
    ]
