# Generated by Django 3.0.3 on 2020-03-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_final_grado', '0002_auto_20200301_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='antecedentes_del_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes'),
        ),
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='identificacion_del_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Identificación del problema'),
        ),
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='planteamiento_del_problema',
            field=models.TextField(blank=True, null=True, verbose_name='Planteamiento del problema'),
        ),
    ]
