# Generated by Django 3.0.3 on 2020-03-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_final_grado', '0003_auto_20200301_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'creado')], default=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='estado_tarea_uno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No gestionado'), (2, 'Creado')], default=1, verbose_name='Estado gestión 1'),
        ),
    ]
