# Generated by Django 3.0.3 on 2020-03-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_final_grado', '0004_auto_20200301_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación'),
        ),
        migrations.AddField(
            model_name='trabajofinalgrado',
            name='fecha_gestion_tarea_uno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha gestión tarea 1'),
        ),
        migrations.AlterField(
            model_name='trabajofinalgrado',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Creado')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='trabajofinalgrado',
            name='estado_tarea_uno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No gestionado'), (2, 'Gestionado')], default=1, verbose_name='Estado gestión 1'),
        ),
    ]
